# Generated by Django 5.2.15 on 2026-06-19 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('Gmail', 'Gmail'), ('WhatsApp', 'WhatsApp')], max_length=20)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('Connected', 'Connected'), ('Disconnected', 'Disconnected')], default='Disconnected', max_length=20)),
                ('connected_email', models.CharField(blank=True, max_length=255, null=True)),
                ('connected_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='tenants.business')),
            ],
            options={
                'unique_together': {('business', 'provider')},
            },
        ),
    ]
