# Generated by Django 5.2.15 on 2026-06-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Opened', 'Opened'), ('Failed', 'Failed'), ('Replied', 'Replied')], default='Pending', max_length=20),
        ),
    ]
