# Generated by Django 5.2.17 on 2026-09-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_description_campaign_message_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='max_interval',
            field=models.PositiveIntegerField(default=0, help_text='Maximum seconds to wait between messages (0 = no delay)'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='min_interval',
            field=models.PositiveIntegerField(default=0, help_text='Minimum seconds to wait between messages (0 = no delay)'),
        ),
    ]
