# Generated by Django 5.2.15 on 2026-06-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_leadcollection_lead_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='business_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='google_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lead',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='user_ratings_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
